name: FFIOpen62541
description: Bindings for open62541
output: 'lib/open62541_bindings.dart'

headers:
  entry-points:
    - 'android/main.c'
    - 'android/open62541.h'
    - 'android/open62541.c'

objc-interfaces:
  exclude:
    - "^(?!UA_)(?!FFI_).*"
    # - "^(?!FFI_).*"

enums:
  exclude:
    - "^(?!UA_)(?!FFI_).*"
    # - "^(?!FFI_).*"

functions:
  exclude:
    - "^(?!UA_)(?!FFI_).*"
    # - "^(?!FFI_).*"

structs:
  exclude:
    - "^(?!UA_)(?!FFI_).*"
    # - "^(?!FFI_).*"

globals:
  exclude:
    - "^(?!UA_)(?!FFI_).*"
    # - "^(?!FFI_).*"
